config/routes.rb
Rails.application.routes.draw do

  root :to => "welcome#index"
  devise_for :users
  resources :people
  resources :events
  resources :scodes
  resources :users

  resources :groups do
    member do
      post :join
      post :quit
    end
    collection do
      get :edit_multiple
      put :update_multiple
    end
    resources :posts
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  get "groups/close/:id" => "groups#close"
  
  namespace :account do
    resources :groups
    resources :posts
      get "/posts/closed" => "posts#closed"
  end

end

  #   end

app/models/group.rb
class Group < ActiveRecord::Base
  
  #has_many :posts
  #validates :title, :presence => true
  
belongs_to :owner, :class_name => "User", :foreign_key => :user_id
has_many :posts, :dependent => :destroy
has_many :group_users
has_many :members, :through => :group_users, :source => :user
validates :title, :presence => true


def editable_by?(user)
user && user == owner
end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :authenticate_user!
before_action :login_required, :only => [:new, :create, :edit,:update,:destroy]
  def index
    @groups = Group.all
  end
  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
    @fil = params[:postfil]
  end
  def close
    @group = Group.find(params[:id])
    @posts = @group.posts
    @products = %w(open fix verify suggest close)
    @selected_product = params[:product]
  end
  #@posts = @group.posts
  #@fil = params[:postfil]
  def edit_multiple 
    #@group = Group.find(params[:id])
    @posts = Post.find(params[:post_ids])
    #redirect_to action: 'close', id: 1
  end
  def update_multiple
    @posts = Post.update(params[:post_ids].keys, params[:post_ids].values)
    redirect_to groups_url
  end
  def new
    @group = Group.new
  end
  def create
    #@group = Group.new(group_params)
	 @group = current_user.groups.new(group_params)
    if @group.save 
      current_user.join!(@group)
      redirect_to groups_path, :notice => 'ADD GROUP DONE'
    else
      render :new
    end
  end
  def edit
    @group = current_user.groups.find(params[:id])
  end
  #@group = Group.find(params[:id])
  #@post = @group.posts.find(params[:id])
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, :notice => 'Edit Group is done'
    else
      render :edit
    end
  end
  def filter
    @group = Group.find(params[:id])
    @posts = @group.posts
    #@filter = @posts.find(params[:ststus])
  end
  def destroy
    #@group = Group.find(params[:id])
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path, :alert => 'Delete Group'
  end
  def join
    @group = Group.find(params[:id])
    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "ADD GROUP DONE"
    else
      flash[:warning] = "You are the member of group"
    end
    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "logout POST"
    else
      flash[:warning] = "You are not the member XD"
    end
    redirect_to group_path(@group)
  end
private
  def group_params
      params.require(:group).permit(:title, :description, :user_id)
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
#["open","fix","verify","close","suggest"] "#{$post_status[0]}" %>
  def post_status_filter(post_ori, status)
  	i = 0 ; post_return = []
  	post_ori.each do |post|
  		if post.status == "#{status}"
  			post_return[i] = post
  			i += 1
  		end
  	end
  	return post_return
  end

end

app/views/groups/_postview.html.erb
<%# from show.html %>

  <table class="table">
    <thead>
      <tr>
        <th>  POST       </th>
        <th colspan="">  </th>
      </tr>
    </thead>

<%# ["ID", "Platform", "Priority", "Category", "Content",  "Status", "Created_at", "Comment", "Reporter", "Url" ,"Summary", "Edit"] %>    
    <tbody>
      <tr>
      	
        <td width="50">  <%= "#{$post_para_display[0]}" %>     </td>
        <td width="80">  <%= "#{$post_para_display[1]}" %>     </td>
        <td width="40">  <%= "#{$post_para_display[2]}" %>     </td>
        <td width="80">  <%= "#{$post_para_display[3]}" %>     </td>
        <td width="400"> <%= "#{$post_para_display[4]}" %>     </td>
        <td width="100"> <%= "#{$post_para_display[5]}" %>     </td>
        <td width="100"> <%= "#{$post_para_display[6]}" %>     </td>

      <% if @group.editable_by?(current_user) %>
        <td width="300"> <%= "#{$post_para_display[7]}" %>     </td>
        <td width="150"> <%= "#{$post_para_display[11]}" %>    </td>
      <% else %>
        <td width="400"> <%= "#{$post_para_display[7]}" %>     </td>
        <td width="100"> <%= "#{$post_para_display[11]}" %>    </td>
      <% end %>      
      </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>  
      <td></td>
      <td></td>
      <td></td>
    </tr> 
    <% @close_item = [] %>     <% @sugg_item = [] %>

    <% c1 = 0 %>       <% c2 = 0 %>
    <% @posts.each do |post| %> 
      <% if post.status == "close" %>
        <% @close_item[c1] = post %>
        <% c1 = c1 + 1 %>
        <% next %>
      <% end %>
      <% if post.status == "suggest" %>
        <% @sugg_item[c2] = post %>
        <% c2 = c2 + 1 %>
        <% next %>
      <% end %>
      <tr>
      <td>
          <%= link_to("#{post.id}",
                group_post_path(post.group, post),
                :class => "btn btn-default btn-xs")%>  </td>
      <td>    <%= post.explorer %> </td>
      <td>    <%= post.priority %> </td>
      <td>    <%= post.category %> </td>
      <td>    <%= post.content  %> </td>
      <td>    <%= post.status   %> </td>
      <td>    
      <%  a = post.created_at.to_s  %>
      <%= a[2..10] %> </td>
      <% if @group.editable_by?(current_user) %>
        <td><%= post.comment %></td>
        <td>
        <%= link_to('Edit', 
                  edit_group_post_path(post.group, post),
                  :class => "btn btn-info btn-xs") %>
        <%= link_to('Delete', 
                  group_post_path(post.group, post),
                  :method => :delete, 
                  data: { confirm: "Are you sure?" },
                  :class => "btn btn-danger btn-xs") %>
        </td>
      <% else %>
        <td><%= post.comment %></td>      
      <% end %> 
    </tr>
    <% end %> 

    <li> close_item 
    <% @close_item.each do |post| %>
      <%= link_to("#{post.id}",
          group_post_path(post.group, post), 
          :class => "btn btn-default btn-xs")%>  <% end %>
    </li>
    <li> suggest_item 
    <% @sugg_item.each do |post| %>
      <%= link_to("#{post.id}",
          group_post_path(post.group, post), 
          :class => "btn btn-default btn-xs")%>  <% end %>
    </li>

    </tbody>
  </table>

app/views/groups/_test.html.erb
<%# from show.html %>

  <table class="table">
    <thead>
      <tr>
        <th>  test       </th>
        <th colspan="">  </th>
      </tr>
    </thead> 
    <tbody>
      <tr>
      	
        <td width="50">  <%= "#{$post_para_display[0]}" %>     </td>
        <td width="80">  <%= "#{$post_para_display[1]}" %>     </td>
        <td width="40">  <%= "#{$post_para_display[2]}" %>     </td>
        <td width="80">  <%= "#{$post_para_display[3]}" %>     </td>
        <td width="400"> <%= "#{$post_para_display[4]}" %>     </td>
        <td width="100"> <%= "#{$post_para_display[5]}" %>     </td>
        <td width="100"> <%= "#{$post_para_display[6]}" %>     </td>

      <% if @group.editable_by?(current_user) %>
        <td width="300"> <%= "#{$post_para_display[7]}" %>     </td>
        <td width="150"> <%= "#{$post_para_display[11]}" %>    </td>
      <% else %>
        <td width="400"> <%= "#{$post_para_display[7]}" %>     </td>
        <td width="100"> <%= "#{$post_para_display[11]}" %>    </td>
      <% end %>      
      </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>  
      <td></td>
      <td></td>
      <td></td>
    </tr> 

    <% @post_return.each do |post| %> 
      <tr>
      <td>
          <%= link_to("#{post.id}",
                group_post_path(post.group, post),
                :class => "btn btn-default btn-xs")%>  </td>
      <td>    <%= post.explorer %> </td>
      <td>    <%= post.priority %> </td>
      <td>    <%= post.category %> </td>
      <td>    <%= post.content  %> </td>
      <td>    <%= post.status   %> </td>
      <td>    
      <%  a = post.created_at.to_s  %>
      <%= a[2..10] %> </td>
      <% if @group.editable_by?(current_user) %>
        <td><%= post.comment %></td>
        <td>
        <%= link_to('Edit', 
                  edit_group_post_path(post.group, post),
                  :class => "btn btn-info btn-xs") %>
        <%= link_to('Delete', 
                  group_post_path(post.group, post),
                  :method => :delete, 
                  data: { confirm: "Are you sure?" },
                  :class => "btn btn-danger btn-xs") %>
        </td>
      <% else %>
        <td><%= post.comment %></td>      
      <% end %> 
    </tr>
    <% end %> 


    </tbody>
  </table>

app/views/groups/close.html.erb
<div class="col-md-12">

  <th class="text-center"> <b>結案區</b></th>
  <br>

<%= form_tag edit_multiple_groups_path, method: :get do %>
  <table>
    <tr>
      <td></td>
      <td>summary</td>
      <td>url</td>
      <td>reporter</td>
    </tr>
  <% @posts.each do |post| %>
  <tr>
    <td> <%= check_box_tag "post_ids[]", post.id %> </td>
    <td> <%= post.summary %>  </td>
    <td> <%= post.url %>  </td>
    <td> <%= post.reporter %>  </td>
  </tr>
  <% end %>
</table>
<%= submit_tag "Edit checked" %> 
<% end %>

<% if false %>
  <% form_tag  :method => :put do %> 
  <% for post in @posts %>
      <%= check_box_tag "post_stas[]", post.id %>
      <%= post.status %>
  <% end %>
  <% end %>
  <br>
  <%= submit_tag "Mark as Complete" %>
<% end %>

<%# ["ID", "Platform", "Priority", "Category", "Content",  "Status", "Created_at", "Comment", "Reporter", "Url" ,"Summary", "Edit"] %>
  <div class="group">
  <table class="table">
    <tbody>
      <tr>
        <td width="50">  <%= "#{$post_para_display[0]}" %>    </td>
        <td width="60">  <%= "#{$post_para_display[1]}" %>    </td>
        <td width="40">  <%= "#{$post_para_display[2]}" %>    </td>
        <td width="80">  <%= "#{$post_para_display[3]}" %>    </td>
        <td width="400"> <%= "#{$post_para_display[4]}" %>    </td>
        <td width="100"> <%= "#{$post_para_display[5]}" %>    </td>      
        <td width="400"> <%= "#{$post_para_display[7]}" %>    </td>
        <td width="150"> <%= "#{$post_para_display[11]}" %>   </td>           
      </tr>
      <tr>
        <td>   </td>
        <td>   </td>
        <td>   </td>
        <td>   </td>
        <td>   </td>
        <td>   <%= select_tag "product", options_for_select(@products, @selected_product) %>   </td>  
        <td>   <%= @selected_product %>     </td>
      </tr>

  <% @posts.each do |post| %> 
      <% if post.status == "close" %>
      <% else %>
        <% if post.status == "suggest" %>
        <% else %>
          <% next %>
        <% end %>
      <% end %>
    <tr>
      <td>      
          <%= link_to("#{post.id}", 
                group_post_path(post.group, post), 
                :class => "btn btn-default btn-xs")%>  </td> 
      <td>    <%= post.explorer %> </td>
      <td>    <%= post.priority %> </td>
      <td>    <%= post.category %> </td>
      <td>    <%= post.content %>  </td>
      <td>    <%= post.status %>   </td>

      <% if @group.editable_by?(current_user) %>
        <td><%= post.comment %></td>
        <td>
        <%= link_to('Edit', 
                  edit_group_post_path(post.group, post), 
                  :class => "btn btn-info btn-xs") %>
        <%= link_to('Delete', 
                  group_post_path(post.group, post),
                  :method => :delete, 
                  data: { confirm: "Are you sure?" },
                  :class => "btn btn-danger btn-xs") %>
        </td>
      <% else %>
        <td><%= post.comment %></td>      
      <% end %> 
    </tr>
  <% end %>      
    </tbody>
  </table>
  </div>
</div>


<div class="container">
<%# params.each do |key, value| %>
  <%#= content_tag(:div, key, class: "alert alert-#{key}") %>
<%# end %>
</div>



<%= Time.now %>
<p><%= link_to 'Back page', :controller => 'groups', :action => 'show' %></p>

app/views/groups/edit.html.erb
<div class="span12">

<%= simple_form_for @group do |f| %>
  <%= f.input :title, :input_html => { :class => "input-xxlarge"} %>
  <%= f.input :description, :input_html => { :class => "input-xxlarge"} %>
  <%#= f.input :user_id, :input_html => { :class => "input-xxlarge"} %>

  <div class="form-actions">
    <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
  </div>
<% end %>

</div>
 
 

app/views/groups/edit_multiple.html.erb
<h1> Edit Checked Products </h1>

<%= form_tag update_multiple_groups_path, method: :put do %>
<% @posts.each do |post| %>
  <h2> <%= post.id %> </h2>
  <%= fields_for "post_ids[]", post do |f| %>
  <% if post.errors.any? %>
  <div id="error_explanation">
  	<h2> <%= pluralize(post.errors.count, "error") %> prohibited this product from being saved:</h2>
  	<ul>
  		<% post.errors.full_messages.each do |msg| %>
  		<li> <%= msg %> </li>
  		<% end %>
  	</ul>
  </div>
  <% end %>

    <div class="field">
	  <%= f.label :id %> <br />
	  <%= f.text_field :id %> 
    </div>
    <div class="field">
	  <%= f.label :summary %> <br />
	  <%= f.text_field :summary %> 
    </div>
    <div class="field">
	  <%= f.label :url %> <br />
	  <%= f.text_field :url %> 
    </div>
    <div class="field">
	  <%= f.label :reporter %> <br />
	  <%= f.text_field :reporter %> 
    </div>
<%= submit_tag "Update" %>

<% end %>
 <% end %>
<% end %>

app/views/groups/index.html.erb
<div class="col-md-12"> 
  <div class="group">
    
    <%= link_to("New group", new_group_path , :class => "btn btn-primary pull-right" ) %>
    <p> </p>
    
  </div>

  <table class="table table-hover">
    <thead> 
      <tr>
        <td> # </td>
        <td> Title </td>
        <td> Description </td>
        <td> Post Accout </td>
      </tr>
    </thead>

    <tbody>
            <% @groups.each do |group| %> 
    <tr>
      <td> # </td>
      <td>  <%= link_to(group.title, group_path(group)) %> </td>
      <td>  <%= group.description %> </td>
      <td>  <%= group.posts.count %> </td> 
      <td>  
            <% if current_user && group.editable_by?(current_user) %>
              <%== link_to("Edit", 
                          edit_group_path(group), 
                          :class => "btn btn-sm btn-default")%>
              <%# link_to("Delete", 
                          group_path(group), 
                          :class => "btn btn-sm btn-default", 
                          :method=>:delete,
                          data: { confirm: "Are you sure?" } )%>
            <% end %>
		  </td> 
    </tr>
            <% end %> 
    </tbody>
  </table>

</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
<h1>Add New Group</h1>

<hr>
<%= simple_form_for @group do |f| %>
  <%= f.input :title, :input_html => { :class => "form-control"} %>
  <%= f.input :description, :input_html => { :class => "form-control"} %>
<hr>
  <%= f.submit "Submit", :disable_with => 'Submitting...', :class => "btn btn-primary"%> 
<% end %> 
</div>

app/views/groups/show.html - 複製.erb
<div class="span12">
<div class="group pull-right">

<%= link_to("Group Edit", edit_group_path(@group) , :class => "btn btn-mini ")%>


</div>

<h2> <%= "GROUP Title :" +  @group.title %> </h2>
<p> <%= "Group Description :" + @group.description %> </p>

<table class="table">
<%= link_to("New Post", new_group_post_path(@group) , :class => "btn btn-minibtn-primary")%>
<tbody>
<% @posts.each do |post| %>
<tr>
<td> <%= post.content %> </td>
<td> <%= link_to("Edit", edit_group_post_path(post.group, post), :class => "btn btn-mini")%>
<%= link_to("Delete", group_post_path(post.group, post), :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?" ) %> </td>
</tr>
<% end %>
</tbody>
</table>

<p><%= link_to 'back to index', groups_path %></p>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <% if @group.editable_by?(current_user) %>
      <%= link_to 'Close item!', { :action => "close" }, :class => "btn btn-warning pull-right" %>
      <%= link_to("Edit Group", edit_group_path(@group) , :class => "btn btn-primary pull-right") %>
      <%= link_to("New Post", new_group_post_path(@group) , :class => "btn btn-warning pull-right")%>
    <% else %>
        <%= link_to 'Close item!', { :action => "close" }, :class => "btn btn-warning pull-right" %>
    <% end %>

    <% if !current_user.nil? %>  
      <% if current_user.is_member_of?(@group) %>
        <% quit_group = "Now at GROUP : " + "#{@group.title}" %>
        <%= link_to("#{quit_group}" , quit_group_path(@group), :method => :post, :class => "btn btn-info") %>
      <% else %>
        <%= link_to("Join Group", join_group_path(@group), :method => :post, :class => "btn btn-info") %>
      <% end %>
    <% end %>
  </div>

  <%= render 'postview' %>

</div>

<p><%= link_to 'Back to GROUP page', :controller => 'groups', :action => 'index' %></p>
<br>

<%= Time.now %>
