config/routes.rb
Rails.application.routes.draw do

  root :to => "welcome#index"
  devise_for :users
  resources :people
  resources :events
  resources :scodes
  resources :users

  resources :groups do
    member do
      post :join
      post :quit
    end
    collection do
      get :edit_multiple
      put :update_multiple
    end
    resources :posts
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  get "groups/close/:id" => "groups#close"
  
  namespace :account do
    resources :groups
    resources :posts
      get "/posts/closed" => "posts#closed"
  end

end

  #   end

app/models/event.rb
class Event < ActiveRecord::Base
	#validates_presence_of :name
	scope :pub, where( :is_public => true )
    scope :recent_three_days, where(["created_at > ? ", Time.now - 3.days ])
end

Event.create( :name => "public event",  :is_public => true )
Event.create( :name => "private event", :is_public => false )
Event.create( :name => "private event", :is_public => true )

#Event.public
#Event.public.recent_three_days

app/controllers/events_controller.rb
class EventsController < ApplicationController
#before_filter :find_event, :only => [ :show, :edit, :update, :destroy]
def index
  @events = Event.all
  #@events = Event.page(params[:page]).per(5)
    respond_to do |format|
    format.html # index.html.erb
    format.xml { render :xml => @events.to_xml }
    format.json { render :json => @events.to_json }
    format.atom { @feed_title = "My event list" } # index.atom.builder
  end
  
end
def new
  @event = Event.new
end
def create
	@event = Event.new(event_params)
  #@event = Event.new(params[:event])
  @event.save

  redirect_to events_url
end
def show
  @event = Event.find(params[:id])
  @page_title = @event.name
  
    respond_to do |format|
    format.html { @page_title = @event.name } # show.html.erb
    format.xml # show.xml.builder
    format.json { render :json => { :id => @event.id, :name => @event.name }.to_json }
  end
end
def edit
  @event = Event.find(params[:id])
end
def update
  @event = Event.find(params[:id])
  @event.update_attributes(event_params)

  redirect_to event_url(@event)
end
def destroy
  @event = Event.find(params[:id])
  @event.destroy
  flash[:alert] = "event was successfully deleted"
  redirect_to events_url
end
end
private
def event_params
params.require(:event).permit(:name, :description, :name)
end
#def find_event
 # @event = Event.find(params[:id])
#end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/version2/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>



app/views/events/version2/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :put do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/version2/index.html.erb

<% @events.each do |event| %>
  <li>
    <%= link_to event.name %>
	<%= link_to 'show', event_path(event) %>
    <%= link_to 'edit', edit_event_path(event) %>
    <%= button_to 'delete', event_path(event), :method => :delete %>
  </li>
<% end %>
</ul>

<%= link_to 'new event', new_event_path %>

app/views/events/version2/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/version2/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'back to index', events_path %></p>