config/routes.rb
Rails.application.routes.draw do

  root :to => "welcome#index"
  devise_for :users
  resources :people
  resources :events
  resources :scodes
  resources :users

  resources :groups do
    member do
      post :join
      post :quit
    end
    collection do
      get :edit_multiple
      put :update_multiple
    end
    resources :posts
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  get "groups/close/:id" => "groups#close"
  
  namespace :account do
    resources :groups
    resources :posts
      get "/posts/closed" => "posts#closed"
  end

end

  #   end

app/models/scode.rb
class Scode < ActiveRecord::Base
end

app/controllers/scodes_controller.rb
class ScodesController < ApplicationController
  def index
    @scodes = Scode.all
  end
  def new
    @scode = Scode.new
  end
  def create
    @scode = Scode.new(scode_params)
    @scode.save
    redirect_to :action => :index
  end
  def show
    @scode = Scode.find(params[:id])
  end
  def edit
    @scode = Scode.find(params[:id])
  end
  def update
    @scode = Scode.find(params[:id])
    @scode.update_attributes(scode_params)
    redirect_to :action => :show, :id => @scode
  end
  def destroy
    @scode = Scode.find(params[:id])
    @scode.destroy
    redirect_to :action => :index
  end
end
private
  def scode_params
    params.require(:scode).permit(:comment, :description, :content, :require)
  end

app/helpers/scodes_helper.rb
module ScodesHelper
end

app/views/scodes/edit.html.erb
<%# form_for @scode, :url => { :controller => 'scodes', :action => 'update', :id => @scode } do |f| %>
<%= form_for @scode, :url => scode_path(@scode), :method => :put do |f| %>
    <%= f.label :comment, "comment" %>
    <%= f.text_field :comment %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
	
    <%= f.label :content, "content" %>
    <%= f.text_area :content %>	

    <%= f.label :require, "require" %>
    <%= f.text_area :require %>
	
    <%= f.submit "Update" %>
<% end %>

app/views/scodes/index.html.erb

<table border="2", width="1000">
  <tr>
    <td width="20">  <b> id         </b></td>
    <td width="150"> <b> Desciption </b></td>
    <td width="500"> <b> content    </b></td>
    <td width="240", align="center", colspan ="3"><b> EDIT </b></td>
  </tr>

  <% @scodes.each do |line| %>
  <tr> 
    <td width="20", align="center"><%= line.id %></td>
    <td width="150"> <%= line.description %> </td>
    <td width="500", height="50"><%= line.content %></td>  
    <td width="80"><%= link_to 'Show', line %></td>
    <td width="80"><%= link_to 'Edit', edit_scode_path(line) %></td>
    <td width="80"><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tr>
</table>

<%= link_to 'new scode', new_scode_path %>


<% if false %>
  <th colspan="3"></th>
  <td width="80"><%= link_to 'Show', :controller => 'scodes', :action => 'show', :id => line %></td>
  <td width="80"><%= link_to 'Edit', :controller => 'scodes', :action => 'edit', :id => line %></td>
  <td width="80"><%= link_to 'delete', scode_path(line), :method => :delete %></td>
<% end %>



app/views/scodes/new.html.erb
<%# form_for @scode, :url => { :controller => 'scodes', :action => 'create' } do |f| %>
<%= form_for @scode, :url => scodes_path do |f| %>
    <%= f.label :comment, "comment" %>
    <%= f.text_field :comment %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.label :content, "content" %>
    <%= f.text_area :content %>	

    <%= f.label :require, "require" %>
    <%= f.text_area :require %>

	
    <%= f.submit "Create" %>
<% end %>

app/views/scodes/show.html.erb

<table border="1", width="600">
  <tr>
    <td width="150"> comment </td>
   	<td width="150"> desciption </td>
	  <td width="150"> content  </td>
	  <td width="150"> require </td>
  </tr>
  <tr>
    <td width="150"> <%= @scode.comment %> </td>
    <td width="150", align="center"><%= simple_format(@scode.description) %></td>
    <td width="150"><%= simple_format(@scode.content) %></td>
    <td width="150"><%= simple_format(@scode.require) %></td>
  </tr>
</table>

<%= link_to 'Back to index', :controller => 'scodes', :action => 'index' %></p>